### ISSUE TITLE
New API Key for DIP API

### ISSUE THREAD

**Issue by hejjoe** [okfde/dokukratie#10]
The old key is used here: 
https://github.com/okfde/dokukratie/blob/main/dokukratie/dip.yml#L25
https://github.com/okfde/dokukratie/blame/main/README.md#L290

N64VhW8
> Zur Nutzung ist ein API-Key notwendig. Der zunächst bis Ende Mai 2023 gültige API-Key lautet:
> GmEPb1B.bfqJLIhcGAsH9fTJevTglhFpCoZyAAAdhp
> 
> Auf Anfrage können Sie auch einen eigenen API Key erhalten, der zeitlich unbefristet ist.
> 
> Bitte stellen Sie eine diesbezügliche Anfrage per E-Mail an: parlamentsdokumentation@bundestag.de

https://dip.bundestag.de/%C3%BCber-dip/hilfe/api#content

**Comment by simonwoerpel** [comment]
thanks for pointing out. we are using the new public api key now.
